docker:
    network-name: "ethereum-testnet"
    ip-subnet: "10.0.20.0/24" 
    volumes: ['./data:/data/', './:/source/']
    # for writing the docker-compose.yaml
files:
  # all files with respect to docker path
  testnet-root: '/data/'

  # execution genesis files.
  geth-genesis-file: "/data/geth-genesis.json"
  besu-genesis-file: "/data/besu-genesis.json"
  nether-mind-genesis-file: "/data/nethermind-genesis.json" # nethermind cares about envargs

  consensus-config-file: "/data/consensus-config.yaml"
  consensus-genesis-file: "/data/genesis.ssz"

  etb-config-file: "/data/etb-config.yaml"
  testnet-dir: "/data/local_testnet" # where client setups occur
    #  execution-bootstrap-dir: "/data/local_testnet/execution-bootstrapper"
  docker-compose-file:  "/source/docker-compose.yaml" #wrt to docker config
  # this file is created when all testnet directories have been written.
  consensus-checkpoint-file: "/data/consensus-clients-ready"
  #this file is written with its time for the first execution client to come up.
  execution-checkpoint-file: "/data/execution-clients-ready"
  # execution client bootnode/bootstrapper. Contains enode+\n for all bootstrap
  consensus-bootnode-checkpoint-file: "/data/consensus-bootnodes-ready"
  # nodes
  execution-enode-file: "/data/execution-bootstrapper/enodes.txt"
  # the enr for the bootnode we chose.


config-params:
  
  deposit-contract-address: "0x8c594691c0e592ffa21f153a16ae41db5befcaaa"

  # used for configuring execution genesis
  execution-layer:
    seconds-per-eth1-block: 14
    execution-genesis-delay: 0
    chain-id: 0x01000666
    network-id: 0x01000666
    merge-fork-block: 127 # consensus epoch 4 eth1_blocks + eth1-follow-distance
    terminal-total-difficulty: 256 # mergeForkBlock*2 + a little more.
    terminal-block-hash: "0x0000000000000000000000000000000000000000000000000000000000000000"
    terminal-block-hash-activation-epoch: 18446744073709551615
    # for now this always needs to be true.
    clique:
      clique-enabled: True
      clique-signers: 
        "51Dd070D1f6f8dB48CA5b0E47D7e899aea6b1AF5"
      clique-epoch: 3000

    # the first execution node that comes alive to bootstrap the network.
    execution-bootstrapper: "geth-bootstrapper"

  # used for generating the consensus config placed in /data/eth2-config.yaml
  consensus-layer:
    consensus-genesis-delay: 225 # eth1-follow-distance*seconds-per-eth1-block + 1
    preset-base: 'mainnet'
    min-genesis-active-validator-count: 20 # custom preseeded into genesis state.
    eth1-follow-distance: 16 # allow past eth1 blocks to be processed.

    forks:
      genesis-fork-version: 0x01000666
      genesis-fork-name: "phase0"
      end-fork-name: "bellatrix"

      phase0-fork-version: 0x01000666
      phase0-fork-epoch: 0 # genesis

      altair-fork-version: 0x02000666
      altair-fork-epoch: 2 # slot 64

      bellatrix-fork-version: 0x03000666
      bellatrix-fork-epoch: 4 # slot 128

      sharding-fork-version: 0x04000666
      sharding-fork-epoch: 18446744073709551615

accounts:
  eth1-account-mnemonic: "cat swing flag economy stadium alone churn speed unique patch report train"
  eth1-passphrase: "testnet-password"
  eth1-premine:
      "m/44'/60'/0'/0/0" : "100000000"
      "m/44'/60'/0'/0/1" : "100000000"
      "m/44'/60'/0'/0/2" : "100000000"
      "m/44'/60'/0'/0/3" : "100000000"

  validator-mnemonic: "ocean style run case glory clip into nature guess jacket document firm fiscal hello kite disagree symptom tide net coral envelope wink render festival" 
  withdrawl-mnemonic: "scatter supreme field crazy unveil chronic favorite middle front umbrella mutual gentle word wild economy dress whale whip method office report eternal garment parrot"

execution-bootnode-configs:
  base-execution-bootnode:
    execution-bootnode-start-ip-addr: "10.0.20.210"
    execution-bootnode-disc-port: 666
    execution-bootnode-private-key: "522d5e0fd25b33b2d9a28c0376013c3704aa79c1dc5424d107531f22d54f9d58"
    execution-bootnode-enode: "enode://d87b29dcf9ab5b2e6f36c83b0c58a3f97b049e743b0e57fa643d6fa2fc8de417307c8a94bb9e54f8ddc9bcc66ac142e241249d177872ca622981f9f8395d6449"
    execution-bootnode-enode-file: "/data/execution-bootnode/enode.txt"
    execution-bootnode-enode-dir: "/data/execution-bootnode"
    num-nodes: 1 # not implemented and must be 1
    execution-bootnode-verbosity: 4

consensus-bootnode-configs:
  eth2-bootnode-config:
    consensus-bootnode-start-ip-addr: "10.0.20.201"
    consensus-bootnode-private-key: "bc971f814d7bd37f7502cc67408c4f2c5a06e1b3d48dc041e42b5478154df1a8" # private key for the bootnode to use
    consensus-bootnode-enr-port: 9001 #port in the enr  
    consensus-bootnode-api-port: 6000 # port for web api.
    consensus-bootnode-enr-file: "/data/eth2-bootnode-enr.dat"
    num-nodes: 1 # not implemented must be 1


execution-bootnodes:
  # currently not working correctly. use /source/apps/really-dumb-peering-workaround.py
  # geth-bootnode:
  #   client-name: "geth-bootnode"
  #   image: "bootnode-client"
  #   tag: "latest"
  #   start-ip-addr: "10.0.20.210" # must match the execution-config
  #   entrypoint: "/source/apps/launchers/bootnodes/launch-geth-bootnode.sh"

  #   num-nodes: 1 # not implemented must be 1 and match the execution-bootnode-config
  #   execution-bootnode-config: "base-execution-bootnode"


consensus-bootnodes:
  eth2-bootnode:
    # args for docker-compose
    client-name: "eth2-bootnode"
    container-name: "eth2-bootnode"
    image: "bootnode-client"
    tag: "latest"
    start-ip-addr: "10.0.20.201"
    entrypoint: "/source/apps/launchers/bootnodes/launch-eth2-bootnode.sh"
    num-nodes: 1 # not implemented must be 1 and match the consensus-bootnode-config

    consensus-bootnode-config: "eth2-bootnode-config"

execution-configs:

  geth-execution-config:
    client: "geth"
    execution-log-level: "4" # detail
    http-apis: "clique,admin,net,eth,web3,personal,engine"
    ws-apis: "clique,admin,net,eth,web3,personal,engine"
    execution-http-port: 8645
    execution-ws-port: 8646
    execution-p2p-port: 666
    execution-engine-auth-port: 8551  
    #execution-engine-port: 8645 
    #execution-engine-ws-port: 8646
    #execution-engine-ws-auth-port: 8552
  besu-execution-config:
    client: "besu"
    execution-log-level: "info"
    http-apis: "ADMIN,MINER,CLIQUE,ETH,NET,DEBUG,TXPOOL,ENGINE"
    ws-apis: "ADMIN,MINER,CLIQUE,ETH,NET,DEBUG,TXPOOL,ENGINE"
    execution-http-port: 8645
    execution-ws-port: 8646
    execution-p2p-port: 666

consensus-configs:

  base-consensus-client:
    num-validators: 4       # number of validators for every client node
    # start ports increment each time we have a node.

    consensus-p2p-port: 4000    # start port used for discovery
    beacon-api-port: 5000   # start port used for the beacon rest API
    beacon-rpc-port: 5500
    validator-rpc-port: 6500
    beacon-metric-port: 8000 # start port used for beacon node metrics.
    validator-metric-port: 9000 # start port used for validator client metrics.
    # entrypoints placed here are used by the consensus clients

    http-web3-ip-addr: "127.0.0.1"
    ws-web3-ip-addr: "127.0.0.1"


execution-clients:
  # the origianl node that starts the network.
  geth-bootstrapper:
    client-name: "geth-bootstrapper"
    container-name: "geth-bootstrapper"
    start-ip-addr: "10.0.20.2"
    image: "geth-client"
    tag: "merge-kiln-v2"
    depends: "ethereum-testnet-bootstrapper"
    entrypoint: "/source/apps/launchers/execution-clients/launch-geth-clique.sh" #wrt to docker.

    execution-config: "geth-execution-config"
    num-nodes: 1
    execution-data-dir: '/data/local_testnet/execution-bootstrapper'
      #jwt-secret-file: "/data/execution-bootstrapper-jwt-secret"  # when the bootstrapper creates this, geth hasn't come up.
    debug: False

    additional-env:
      geth-password-file: "/data/geth-account-passwords.txt"
      is-mining: True
      eth1-passphrase: "testnet-password"
      clique-unlock-key: "51Dd070D1f6f8dB48CA5b0E47D7e899aea6b1AF5"
  # besu-bootstrapper: 
  #   client-name: "besu"
  #   container-name: "besu-bootstrapper"
  #   start-ip-addr: "10.0.20.2"
  #   image: "besu"
  #   tag: "main"
  #   depends: "ethereum-testnet-bootstrapper"
  #   entrypoint: "/source/apps/launchers/execution-clients/launch-bootstrapper-besu-clique.sh" #wrt to docker.
  #   execution-config: "besu-execution-config"
  #   num-nodes: 1
  #   data-dir: '/data/local_testnet/execution-bootstrapper'
  #   debug: False

  #   additional-env:
  #     besu-private-key: "0x1e48147d3eb2af708706c71188703913e3b2dead2716dbe0caa8ccf4ff1d5573"

consensus-clients:
  # nimbus nodes whose deposits were done pre-genesis
  prysm-besu:
    client-name: 'prysm'
    # docker-compose
    image: "prysm-client"
    tag: "kilnv2"
    container-name: "prysm-client-besu"
    entrypoint: "/source/apps/launchers/consensus-clients/launch-prysm.sh"
    start-ip-addr: "10.0.20.10"
    depends: "ethereum-testnet-bootstrapper"
    # beacon/validator flags
    num-nodes: 1 # how many beacon nodes
    consensus-config: "base-consensus-client"

    consensus-bootnode-config: "eth2-bootnode-config"

    local-execution-client: true
    execution-config: "besu-execution-config"
    execution-launcher: "/source/apps/launchers/execution-clients/launch-besu-clique.sh"


    testnet-dir: '/data/local_testnet/prysm-besu'

    validator-offset-start: 0 # so validators of different clients don't overlap
    # args specific to prysm nodes, these are loaded into the dockers env at runtime.
    additional-env:
      prysm-debug-level: "debug"
      wallet-path: '/data/local_testnet/prysm-besu/wallet-password.txt'
      validator-password: "testnet-password"


  teku-besu:
    client-name: 'teku'
    # docker-compose
    image: "teku-client"
    tag: "kilnv2"
    container-name: "teku-client-besu"
    entrypoint: "/source/apps/launchers/consensus-clients/launch-teku.sh"
    start-ip-addr: "10.0.20.20"
    depends: "ethereum-testnet-bootstrapper"

    num-nodes: 1 # how many beacon nodes
    consensus-config: "base-consensus-client"

    consensus-bootnode-config: "eth2-bootnode-config"
    local-execution-client: true
    execution-config: "besu-execution-config"
    execution-launcher: "/source/apps/launchers/execution-clients/launch-besu-clique.sh"

    testnet-dir: '/data/local_testnet/teku-besu'

    validator-offset-start: 4 # so validators of different clients don't overlap

    # args specific to teku nodes.
    additional-env:
      teku-debug-level: "DEBUG"


  nimbus-besu:
    client-name: 'nimbus'
    # docker-compose
    image: "nimbus-client"
    tag: "kilnv2"
    container-name: "nimbus-client-besu"
    entrypoint: "/source/apps/launchers/consensus-clients/launch-nimbus.sh"
    start-ip-addr: "10.0.20.30"
    depends: "ethereum-testnet-bootstrapper"

    num-nodes: 1 # how many beacon nodes
    testnet-dir: '/data/local_testnet/nimbus-besu'

    consensus-config: "base-consensus-client"
    consensus-bootnode-config: "eth2-bootnode-config"

    local-execution-client: true
    execution-config: "besu-execution-config"
    execution-launcher: "/source/apps/launchers/execution-clients/launch-besu-clique.sh"

    validator-offset-start: 8 # so validators of different clients don't overlap

    additional-env:
      nimbus-debug-level: "trace"


  lighthouse-besu:
    client-name: 'lighthouse'
    # docker-compose
    image: "lighthouse-client"
    tag: "kilnv2"
    container-name: "lighthouse-client-besu"
    entrypoint: "/source/apps/launchers/consensus-clients/launch-lighthouse.sh"
    start-ip-addr: "10.0.20.40"
    depends: "ethereum-testnet-bootstrapper"

    consensus-config: "base-consensus-client"
    consensus-bootnode-config: "eth2-bootnode-config"

    local-execution-client: true
    execution-config: "besu-execution-config"
    execution-launcher: "/source/apps/launchers/execution-clients/launch-besu-clique.sh"

    num-nodes: 1 # how many beacon nodes
    testnet-dir: '/data/local_testnet/lighthouse-besu'
    validator-offset-start: 12 # so validators of different clients don't overlap
    
    additional-env:
      lighthouse-debug-level: "debug"


  lodestar-besu:
    client-name: 'lodestar'
    # docker-compose
    image: "lodestar-client"
    tag: "kilnv2"
    container-name: "lodestar-client-besu"
    entrypoint: "/source/apps/launchers/consensus-clients/launch-lodestar.sh"
    start-ip-addr: "10.0.20.50"
    depends: "ethereum-testnet-bootstrapper"
  
    num-nodes: 1 # how many beacon nodes
    consensus-config: "base-consensus-client"
    consensus-bootnode-config: "eth2-bootnode-config"
  
    local-execution-client: true
    execution-config: "besu-execution-config"
    execution-launcher: "/source/apps/launchers/execution-clients/launch-besu-clique.sh"
  
    testnet-dir: '/data/local_testnet/lodestar-besu'
    validator-offset-start: 16 # so validators of different clients don't overlap
    
    additional-env:
      lstar-debug-level: "debug"

# required.
testnet-bootstrapper:
  ethereum-testnet-bootstrapper:
    #docker-compose
    image: "ethereum-testnet-bootstrapper"
    tag: "latest"
    container-name: "testnet-bootstrapper"
    start-ip-addr: "10.0.20.202"
    num-nodes: 1
    entrypoint: "/source/entrypoint.sh --config /data/etb-config.yaml --bootstrap-testnet --log-level debug"

generic-modules:
  tx-fuzzer:
    client-name: "tx-fuzzer"
    container-name: "tx-fuzzer"
    start-ip-addr: "10.0.20.222"
    image: "teku-client" # we just need a client that has tx-fuzzer and the execution client.
    tag: "kilnv2"
    depends: "ethereum-testnet-bootstrapper"
    entrypoint: "/source/apps/launchers/fuzzers/launch-tx-fuzzer.sh"
    num-nodes: 1

    additional-env:
      tx-fuzz-enabled: True
      tx-fuzz-private-keys: "0x1e48147d3eb2af708706c71188703913e3b2dead2716dbe0caa8ccf4ff1d5573,0x6cf9f64e4bdf9b5547882e276da15a590f0873d313a2a833f07f3ec9d45fdc7e,0x045b49f8c41b5562fbfc54c3d5c76df1cd7b2c340494383b2e3783de81c39184,0xa7c0262c56b2f5b9dd43c7cb544aff29e77e2b2a4ced2a34964016ff4cbf7675"
      tx-fuzz-public-keys: "0x51Dd070D1f6f8dB48CA5b0E47D7e899aea6b1AF5,0x6B477789219c9D5b80159652AA913A5eee39d07e,0xa03f25d5839029323Be765Fbc02E262628923338,0x60337eFAD102533d73E7c7D03736B8c4b87cdB2e"
      tx-fuzz-mode: "spam"
      launch-new-execution-client: False # don't make a new geth node
      http-web3-ip-addr: "10.0.20.2"  # use the geth-bootstrapper
      execution-http-port: 8645       # geth boostrapper arg.

  network-monitor:
    client-name: "network-monitor"
    image: "ethereum-testnet-bootstrapper"
    tag: "latest"
    container-name: "network-monitor"
    start-ip-addr: "10.0.20.206"
    num-nodes: 1
    entrypoint: "python3 /source/apps/network-monitor.py --config /data/etb-config.yaml"
        # status-check:
        #   client-name: "status-check"
        #   image: "ethereum-testnet-bootstrapper"
        #   tag: "latest"
        #   container-name: "status-check"
        #   start-ip-addr: "10.0.20.206"
        #   num-nodes: 1
        #   entrypoint: "python3 /source/apps/status-check.py --config /source/configs/mainnet/testing.yaml --phase0-slot 32 --experiment-slot 128 --phase1-slot 128 --phase2-slot 160 --number-of-checks 2"

  
