# Running a minimal testnet with the current network conditions.
# parameters for building the docker network

# testnet-configuration parameters
testnet-config:
  consensus-layer:
    preset-base: 'minimal'

client-instances:
###############################################################################
####### All Consensus Clients paired with a Geth Execution Client. ############
###############################################################################
  prysm-geth:
    consensus-config: "prysm-consensus-client"
    execution-config: "geth-execution-config"
    additional-env:
      test: "foo"

  teku-geth:
    consensus-config: "teku-consensus-client"
    execution-config: "geth-execution-config"

  lighthouse-geth:
    consensus-config: "lighthouse-consensus-client"
    execution-config: "geth-execution-config"

  lodestar-geth:
    consensus-config: "lodestar-consensus-client"
    execution-config: "geth-execution-config"

  nimbus-geth:
    consensus-config: "nimbus-consensus-client"
    execution-config: "geth-execution-config"

  prysm-besu:
    consensus-config: "prysm-consensus-client"
    execution-config: "besu-execution-config"

  teku-besu:
    consensus-config: "teku-consensus-client"
    execution-config: "besu-execution-config"

  lighthouse-besu:
    consensus-config: "lighthouse-consensus-client"
    execution-config: "geth-execution-config"

  lodestar-besu:
    consensus-config: "lodestar-consensus-client"
    execution-config: "besu-execution-config"

  nimbus-besu:
    consensus-config: "nimbus-consensus-client"
    execution-config: "besu-execution-config"

  prysm-nethermind:
    consensus-config: "prysm-consensus-client"
    execution-config: "nethermind-execution-config"

  teku-nethermind:
    consensus-config: "teku-consensus-client"
    execution-config: "nethermind-execution-config"

  lighthouse-nethermind:
    consensus-config: "lighthouse-consensus-client"
    execution-config: "nethermind-execution-config"

  lodestar-nethermind:
    consensus-config: "lodestar-consensus-client"
    execution-config: "nethermind-execution-config"

  nimbus-nethermind:
    consensus-config: "nimbus-consensus-client"
    execution-config: "nethermind-execution-config"

  prysm-reth:
    consensus-config: "prysm-consensus-client"
    execution-config: "reth-execution-config"

  teku-reth:
    consensus-config: "teku-consensus-client"
    execution-config: "reth-execution-config"

  lighthouse-reth:
    consensus-config: "lighthouse-consensus-client"
    execution-config: "reth-execution-config"

  lodestar-reth:
    consensus-config: "lodestar-consensus-client"
    execution-config: "reth-execution-config"

  nimbus-reth:
    consensus-config: "nimbus-consensus-client"
    execution-config: "reth-execution-config"

# generic instances that run fuzzers/health checks/etc.
generic-instances:
  tx-spammer:
    image: "etb-all-clients"
    tag: "minimal-current"

    entrypoint: "python3 /source/src/tx_spammer.py --target-instance prysm-geth-0 --epoch-delay 1 --fuzz-mode spam --tx-fuzz-path /usr/local/bin/livefuzzer"
